name: Deploy to githubdeploy.wrongs.eu

on:
  push:
    branches:
      - main
      - testpage

jobs:
  deploy:
    name: Build and Sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to public site
        if: github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: githubdeploy.wrongs.eu
          username: d151313f1028978
          password: ${{ secrets.secret }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: /htdocs/

      - name: Deploy to test page
        if: github.ref == 'refs/heads/testpage'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: githubdeploy.wrongs.eu
          username: d151313f1028978
          password: ${{ secrets.secret }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: /htdocs/testpage/