name: Deploy to githubdeploy.wrongs.eu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: FTPS Deploy to Zone
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: githubdeploy.wrongs.eu
          username: d151313f1028978
          password: ${{ secrets.labubu }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: /htdocs/